/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 * 
 */
public class CajeroDineroUI extends javax.swing.JFrame {

    /**
     * Creates new form CajeroDineroUI
     */
    public CajeroDineroUI() {
        initComponents();
        getContentPane().setBackground(new Color(44, 62, 80));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JTextField();
        botonDinero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 240, 241));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dinero nuevo al cajero");

        txtDinero.setBackground(new java.awt.Color(108, 122, 137));
        txtDinero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDinero.setForeground(new java.awt.Color(228, 241, 254));
        txtDinero.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonDinero.setBackground(new java.awt.Color(34, 167, 240));
        botonDinero.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonDinero.setForeground(new java.awt.Color(255, 255, 255));
        botonDinero.setText("Introducir Dinero");
        botonDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDineroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(botonDinero)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt Cogemos los datos introducidos en los txtField y se lo pasamos
     * a una consulta para ingresas dinero en el cajero.
     * 
     */
    private void botonDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDineroActionPerformed
        try {
            int catidad = Integer.parseInt(txtDinero.getText());
            int dineroCajero = ServicioBBDD.totalDinero();
            dineroCajero = dineroCajero + catidad;
            ServicioBBDD.updateCajero(dineroCajero);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Unicamente numeros enteros", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_botonDineroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajeroDineroUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CajeroDineroUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDinero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtDinero;
    // End of variables declaration//GEN-END:variables
}
