/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 * 
 */
public class MenuUsuariosUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuariosUI
     */
    public MenuUsuariosUI() {
        initComponents();
        getContentPane().setBackground(new Color(44, 62, 80));
    }
    
    /**
     * Muestra los usuarios que hay.
     * Con el boolean bloqueamos las celdas que queremos.
     */
    public void muestraUsuarios() {
        List<Usuario> listaUsuarios = ServicioBBDD.getUsuarios();
        DefaultTableModel modelo = new DefaultTableModel(0,3){
        @Override
        public boolean isCellEditable (int row, int column){
            return column == 1 || column == 2;
        }
        };
        for (Usuario usuario : listaUsuarios) {
            int idUsuario = usuario.getIdUsuario();
            String nombre = usuario.getNombre();
            String apellido = usuario.getApellido();
            Object[] datos = {idUsuario,nombre,apellido};
            //Añadir a la tabla
            modelo.addRow(datos);
        }
        modelo.setColumnIdentifiers(new String[]{"ID_Usuario", "Nombre", "Apellido"});
        this.resultados.setModel(modelo);
        modelo.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTable();
        butBorra = new javax.swing.JButton();
        butModifi = new javax.swing.JButton();
        radioUsuarios = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        resultados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Cuenta", "ID_Usuario", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultados);

        butBorra.setBackground(new java.awt.Color(34, 167, 240));
        butBorra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butBorra.setForeground(new java.awt.Color(255, 255, 255));
        butBorra.setText("Borrar");
        butBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBorraActionPerformed(evt);
            }
        });

        butModifi.setBackground(new java.awt.Color(34, 167, 240));
        butModifi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butModifi.setForeground(new java.awt.Color(255, 255, 255));
        butModifi.setText("Modificar");
        butModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifiActionPerformed(evt);
            }
        });

        radioUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioUsuarios.setForeground(new java.awt.Color(236, 240, 241));
        radioUsuarios.setText("Usuarios");
        radioUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU ADMINISTRADOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(butBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(butModifi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioUsuarios)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butBorra)
                    .addComponent(butModifi))
                .addGap(38, 38, 38))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt Para borrar la fila seleccionada.
     * 
     */
    private void butBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBorraActionPerformed
        try {
            if (radioUsuarios.isSelected()) {
            borrarUsuariosSeleccionada();
        }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_butBorraActionPerformed

    /**
     * 
     * @param evt Para modificar la linea seleccionada.
     */
    private void butModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifiActionPerformed
        try {
            int fila = resultados.getSelectedRow();
            if (resultados.isRowSelected(fila)) {
                int idUsuario =  (int) resultados.getValueAt(fila, 0);
                String nombre  = (String) resultados.getValueAt(fila, 1);
                String apellido =   (String) resultados.getValueAt(fila, 2);
                System.out.println(idUsuario);
                System.out.println(nombre);
                System.out.println(apellido);
                ServicioBBDD.updateUsuario(idUsuario,nombre,apellido);
            }
        } catch (ClassCastException ev) {
            JOptionPane.showMessageDialog(this, "Ningun dato actualizado", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_butModifiActionPerformed

    private void radioUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUsuariosActionPerformed
        muestraUsuarios();
    }//GEN-LAST:event_radioUsuariosActionPerformed

    /**
     * Borra la cuenta seleccionada
     */
     public void borrarUsuariosSeleccionada() {
        int indice = this.resultados.getSelectedRow();

        int idUsuario = (int) this.resultados.getValueAt(indice, 0);
        ServicioBBDD.borrarUsuario(idUsuario);
        this.muestraUsuarios();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsuariosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsuariosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsuariosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsuariosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuUsuariosUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBorra;
    private javax.swing.JButton butModifi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioUsuarios;
    private javax.swing.JTable resultados;
    // End of variables declaration//GEN-END:variables
}
