/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 * 
 */
public class MenuCuentasUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrarCuentasUI
     */
    public MenuCuentasUI() {
        initComponents();
        getContentPane().setBackground(new Color(44, 62, 80));
        dispose();

    }

    /**
     * Muestra las cuentas que hay.
     * Con el boolean bloqueamos las celdas que queremos.
     */
    public void muestraCuentas() {
        List<Cuenta> listaCuentas = ServicioBBDD.getCuentas();
        DefaultTableModel modelo = new DefaultTableModel(0, 3) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }
        };
        for (Cuenta cuenta : listaCuentas) {
            int idCuenta = cuenta.getIdCuenta();
            int idUsuario = cuenta.getIdUsuario();
            int saldo = cuenta.getSaldo();
            Object[] datos = {idCuenta, idUsuario, saldo};
            //Añadir a la tabla
            modelo.addRow(datos);
        }
        modelo.setColumnIdentifiers(new String[]{"ID_Cuenta", "ID_Usuario", "Saldo"});
        this.resultados.setModel(modelo);
        modelo.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTable();
        butBorra = new javax.swing.JButton();
        butModifi = new javax.swing.JButton();
        radioCuentas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU ADMINISTRADOR");

        resultados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Cuenta", "ID_Usuario", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultados);

        butBorra.setBackground(new java.awt.Color(34, 167, 240));
        butBorra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butBorra.setForeground(new java.awt.Color(255, 255, 255));
        butBorra.setText("Borrar");
        butBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBorraActionPerformed(evt);
            }
        });

        butModifi.setBackground(new java.awt.Color(34, 167, 240));
        butModifi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butModifi.setForeground(new java.awt.Color(255, 255, 255));
        butModifi.setText("Modificar");
        butModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifiActionPerformed(evt);
            }
        });

        radioCuentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioCuentas.setForeground(new java.awt.Color(236, 240, 241));
        radioCuentas.setText("Cuentas");
        radioCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(butBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(butModifi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(radioCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butModifi))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt Para borrar la fila seleccionada.
     * 
     */
    private void butBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBorraActionPerformed
        try {
            if (radioCuentas.isSelected()) {
            borrarCuentasSeleccionada();
        }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_butBorraActionPerformed

    /**
     * 
     * @param evt Para modificar la linea seleccionada.
     */
    private void butModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifiActionPerformed
        try {
            int fila = resultados.getSelectedRow();
            if (resultados.isRowSelected(fila)) {
                int idCuentas = (int) resultados.getValueAt(fila, 0);
                int idUsuario = (int) resultados.getValueAt(fila, 1);
                int saldo = Integer.parseInt((String) resultados.getValueAt(fila, 2));
                System.out.println(idCuentas);
                System.out.println(idUsuario);
                System.out.println(saldo);
                ServicioBBDD.updateCuenta(idCuentas, saldo);
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Ningun dato actualizado", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_butModifiActionPerformed

    private void radioCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCuentasActionPerformed
        muestraCuentas();
    }//GEN-LAST:event_radioCuentasActionPerformed

    /**
     * Borra la cuenta seleccionada
     */
    public void borrarCuentasSeleccionada() {
        int indice = this.resultados.getSelectedRow();

        int idCuenta = (int) this.resultados.getValueAt(indice, 0);
        ServicioBBDD.borrarCuenta(idCuenta);
        this.muestraCuentas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCuentasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuCuentasUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBorra;
    private javax.swing.JButton butModifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCuentas;
    private javax.swing.JTable resultados;
    // End of variables declaration//GEN-END:variables
}
