/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 * 
 */
public class MenuAdministradorUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministradorUI
     */
    public MenuAdministradorUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jMenu3 = new javax.swing.JMenu();
        labelFoto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuTarjeta = new javax.swing.JMenu();
        menuAnadirTarjeta = new javax.swing.JMenuItem();
        menuAdminTarjeta = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuCuentas2 = new javax.swing.JMenu();
        menuAnadirCuenta = new javax.swing.JMenuItem();
        menuAdminCuentas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuUsuario = new javax.swing.JMenu();
        menuAnadirUsuarios = new javax.swing.JMenuItem();
        menuAdminUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        botonCajero = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        labelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCajero/programaciuon.gif"))); // NOI18N
        getContentPane().add(labelFoto, "card2");

        jMenuBar1.setBackground(new java.awt.Color(248, 148, 6));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(248, 148, 6));
        jMenu1.setText("Principal");

        jMenuItem2.setText("Cambiar Fondo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(menuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(248, 148, 6));
        jMenu2.setText("Administrar");

        menuTarjeta.setText("Tarjetas");

        menuAnadirTarjeta.setText("Añadir Tarjeta");
        menuAnadirTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnadirTarjetaActionPerformed(evt);
            }
        });
        menuTarjeta.add(menuAnadirTarjeta);

        menuAdminTarjeta.setText("Administrar Tarjetas");
        menuAdminTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminTarjetaActionPerformed(evt);
            }
        });
        menuTarjeta.add(menuAdminTarjeta);

        jMenu2.add(menuTarjeta);
        jMenu2.add(jSeparator2);

        menuCuentas2.setText("Cuentas");

        menuAnadirCuenta.setText("Añadir Cuenta");
        menuAnadirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnadirCuentaActionPerformed(evt);
            }
        });
        menuCuentas2.add(menuAnadirCuenta);

        menuAdminCuentas.setText("Administrar Cuentas");
        menuAdminCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminCuentasActionPerformed(evt);
            }
        });
        menuCuentas2.add(menuAdminCuentas);

        jMenu2.add(menuCuentas2);
        jMenu2.add(jSeparator3);

        menuUsuario.setText("Usuario");

        menuAnadirUsuarios.setText("Añadir Usuario");
        menuAnadirUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnadirUsuariosActionPerformed(evt);
            }
        });
        menuUsuario.add(menuAnadirUsuarios);

        menuAdminUsuarios.setText("Administrar Usuarios");
        menuAdminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminUsuariosActionPerformed(evt);
            }
        });
        menuUsuario.add(menuAdminUsuarios);

        jMenu2.add(menuUsuario);
        jMenu2.add(jSeparator1);

        botonCajero.setText("Cajero");
        botonCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCajeroActionPerformed(evt);
            }
        });
        jMenu2.add(botonCajero);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAnadirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnadirCuentaActionPerformed
        AñadirCuentaUI añadir = new AñadirCuentaUI();
        añadir.setVisible(true);
    }//GEN-LAST:event_menuAnadirCuentaActionPerformed

    private void menuAdminCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminCuentasActionPerformed
        MenuCuentasUI menuCu = new MenuCuentasUI();
        menuCu.setVisible(true);
    }//GEN-LAST:event_menuAdminCuentasActionPerformed

    private void menuAnadirUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnadirUsuariosActionPerformed
        AñadirUsuarioUI anadirUsu = new AñadirUsuarioUI();
        anadirUsu.setVisible(true);
    }//GEN-LAST:event_menuAnadirUsuariosActionPerformed

    private void menuAdminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminUsuariosActionPerformed
        MenuUsuariosUI menuUsu = new MenuUsuariosUI();
        menuUsu.setVisible(true);
    }//GEN-LAST:event_menuAdminUsuariosActionPerformed

    /**
     * 
     * @param evt Para añadir una foto.
     * 
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser abrir = new JFileChooser();
        abrir.removeChoosableFileFilter(abrir.getAcceptAllFileFilter());
        FileNameExtensionFilter filPNG = new FileNameExtensionFilter("Extension de imagen", "png","jpg","gif");
        
        abrir.addChoosableFileFilter(filPNG);
        int botonPulsado = abrir.showOpenDialog(this);
        
        File file = abrir.getSelectedFile();
        
        if (botonPulsado == JFileChooser.APPROVE_OPTION) {
            try {
                Image imagen = ImageIO.read(file);
                ImageIcon foto = new ImageIcon(imagen.getScaledInstance(labelFoto.getWidth(), labelFoto.getHeight(), Image.SCALE_AREA_AVERAGING));
                labelFoto.setIcon(foto);
                
                
            } catch (IOException ex) {
                Logger.getLogger(MenuAdministradorUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuAnadirTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnadirTarjetaActionPerformed
        AñadirTarjetaUI añaTar = new AñadirTarjetaUI();
        añaTar.setVisible(true);
    }//GEN-LAST:event_menuAnadirTarjetaActionPerformed

    private void menuAdminTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminTarjetaActionPerformed
        MenuTarjetasUI menuTar = new MenuTarjetasUI();
        menuTar.setVisible(true);
    }//GEN-LAST:event_menuAdminTarjetaActionPerformed

    private void botonCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCajeroActionPerformed
        CajeroDineroUI cajeroDi = new CajeroDineroUI();
        cajeroDi.setVisible(true);
    }//GEN-LAST:event_botonCajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministradorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem botonCajero;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JLabel labelFoto;
    private javax.swing.JMenuItem menuAdminCuentas;
    private javax.swing.JMenuItem menuAdminTarjeta;
    private javax.swing.JMenuItem menuAdminUsuarios;
    private javax.swing.JMenuItem menuAnadirCuenta;
    private javax.swing.JMenuItem menuAnadirTarjeta;
    private javax.swing.JMenuItem menuAnadirUsuarios;
    private javax.swing.JMenu menuCuentas2;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenu menuTarjeta;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
