/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 *
 */
public class MenuTarjetasUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuTarjetasUI
     */
    public MenuTarjetasUI() {
        initComponents();
        getContentPane().setBackground(new Color(44, 62, 80));
    }

    /**
     * Muestra las tarjetas que hay. Con el boolean bloqueamos las celdas que
     * queremos.
     */
    public void muestraTarjetas() {
        List<Tarjeta> listaUsuarios = ServicioBBDD.getTarjetas();
        DefaultTableModel modelo = new DefaultTableModel(0, 4) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2;
            }
        };
        for (Tarjeta tarjeta : listaUsuarios) {
            int idTarjeta = tarjeta.getIdTarjeta();
            int idCuenta = tarjeta.getIdCuenta();
            int pin = tarjeta.getPin();
            int bloqueo = tarjeta.getTarjeta_bloqueo();

            Object[] datos = {idTarjeta, idCuenta, pin, bloqueo};
            //Añadir a la tabla
            modelo.addRow(datos);
        }
        modelo.setColumnIdentifiers(new String[]{"ID_Tarjeta", "ID_Cuenta", "Pin", "Bloqueo"});
        this.resultados.setModel(modelo);
        modelo.fireTableDataChanged();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultados = new javax.swing.JTable();
        butBorra = new javax.swing.JButton();
        butModifi = new javax.swing.JButton();
        radioCuentas = new javax.swing.JRadioButton();
        butBloquear = new javax.swing.JButton();
        butDesbloq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU ADMINISTRADOR");

        resultados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Tarjeta", "ID_Cuenta", "PIN", "Bloqueo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultados);

        butBorra.setBackground(new java.awt.Color(34, 167, 240));
        butBorra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butBorra.setForeground(new java.awt.Color(255, 255, 255));
        butBorra.setText("Borrar");
        butBorra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBorraActionPerformed(evt);
            }
        });

        butModifi.setBackground(new java.awt.Color(34, 167, 240));
        butModifi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butModifi.setForeground(new java.awt.Color(255, 255, 255));
        butModifi.setText("Modificar");
        butModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifiActionPerformed(evt);
            }
        });

        radioCuentas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radioCuentas.setForeground(new java.awt.Color(236, 240, 241));
        radioCuentas.setText("Tarjetas");
        radioCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCuentasActionPerformed(evt);
            }
        });

        butBloquear.setBackground(new java.awt.Color(34, 167, 240));
        butBloquear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butBloquear.setForeground(new java.awt.Color(255, 255, 255));
        butBloquear.setText("Bloquear");
        butBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butBloquearActionPerformed(evt);
            }
        });

        butDesbloq.setBackground(new java.awt.Color(34, 167, 240));
        butDesbloq.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butDesbloq.setForeground(new java.awt.Color(255, 255, 255));
        butDesbloq.setText("Desbloquear");
        butDesbloq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDesbloqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butBorra)
                        .addGap(18, 18, 18)
                        .addComponent(butModifi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butBloquear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butDesbloq))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(radioCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butBorra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butModifi)
                    .addComponent(butBloquear)
                    .addComponent(butDesbloq))
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param evt Para borrar la fila seleccionada.
     *
     */
    private void butBorraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBorraActionPerformed
        try {
            if (radioCuentas.isSelected()) {
                borrarTarjetaSeleccionada();
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_butBorraActionPerformed
    /**
     *
     * @param evt Para modificar la linea seleccionada.
     */
    private void butModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifiActionPerformed
        try {
            int fila = resultados.getSelectedRow();
            if (resultados.isRowSelected(fila)) {
                int idTarjeta = (int) resultados.getValueAt(fila, 0);
                int idCuentas = (int) resultados.getValueAt(fila, 1);
                int pin = Integer.parseInt((String) resultados.getValueAt(fila, 2));
                int bloqueo = (int) resultados.getValueAt(fila, 3);
                System.out.println(idTarjeta);
                System.out.println(idCuentas);
                System.out.println(pin);
                System.out.println(bloqueo);
                ServicioBBDD.updateTarjeta(idTarjeta, idCuentas, pin, bloqueo);
            }
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "Ningun dato actualizado", "Advetencia", JOptionPane.WARNING_MESSAGE);
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_butModifiActionPerformed

    private void radioCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCuentasActionPerformed
        muestraTarjetas();
    }//GEN-LAST:event_radioCuentasActionPerformed

    /**
     * Borra la cuenta seleccionada
     */
    private void butBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butBloquearActionPerformed
        try {
            int indice = this.resultados.getSelectedRow();
            int bloqueo = 1;
            int idTarjeta = (int) this.resultados.getValueAt(indice, 0);
            ServicioBBDD.tarjetaBloqueo(idTarjeta, bloqueo);
            this.muestraTarjetas();
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_butBloquearActionPerformed

    private void butDesbloqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDesbloqActionPerformed
        try {
            int indice = this.resultados.getSelectedRow();
            int desbloqueo = 0;
            int idTarjeta = (int) this.resultados.getValueAt(indice, 0);
            ServicioBBDD.tarjetaDesbloqueo(idTarjeta, desbloqueo);
            this.muestraTarjetas();

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(this, "Ninguna fila seleccionada", "Advetencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_butDesbloqActionPerformed

    public void borrarTarjetaSeleccionada() {
        int indice = this.resultados.getSelectedRow();

        int idTarjeta = (int) this.resultados.getValueAt(indice, 0);
        ServicioBBDD.borrarTarjeta(idTarjeta);
        this.muestraTarjetas();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTarjetasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTarjetasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTarjetasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTarjetasUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTarjetasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butBloquear;
    private javax.swing.JButton butBorra;
    private javax.swing.JButton butDesbloq;
    private javax.swing.JButton butModifi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioCuentas;
    private javax.swing.JTable resultados;
    // End of variables declaration//GEN-END:variables
}
