/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.util.Date;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 * 
 */
public class MovimientosListaUI extends javax.swing.JPanel {

    private final Usuario usuario;
    private final Tarjeta tarjeta;
    private final Cuenta cuenta;
    
    /**
     * Creates new form MovimientosListaUI
     */
    public MovimientosListaUI(Cuenta cuenta, Tarjeta tarjeta,Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        this.tarjeta = tarjeta;
        this.cuenta = cuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMov = new javax.swing.JTable();
        botonVerMovimientos = new javax.swing.JButton();

        setBackground(new java.awt.Color(134, 222, 249));

        jLabel1.setBackground(new java.awt.Color(134, 222, 249));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LISTA DE MOVIMIENTOS");

        tablaMov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tablaMov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Concepto", "Fecha", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaMov.setRowHeight(12);
        jScrollPane1.setViewportView(tablaMov);

        botonVerMovimientos.setBackground(new java.awt.Color(34, 167, 240));
        botonVerMovimientos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botonVerMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        botonVerMovimientos.setText("Ver Movimientos");
        botonVerMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerMovimientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonVerMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(botonVerMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt Para ver lo moviemientos de cada usuario.
     */
    private void botonVerMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerMovimientosActionPerformed
        List<Movimiento>listaMovimiento = ServicioBBDD.getMovimientos(cuenta.getIdCuenta());
        DefaultTableModel modelo = new DefaultTableModel(0, 3);
        
        for (Movimiento movimiento : listaMovimiento) {
            String concepto = movimiento.getConcepto();
            Date fecha = movimiento.getFecha();
            
            int cantidad = movimiento.getCantidad();
            Object [] datos = {concepto, fecha, cantidad};
            //Añadir a la tabla
            modelo.addRow(datos);
        }
        modelo.setColumnIdentifiers(new String[]{"Concepto","Fecha","Cantidad"});
        this.tablaMov.setModel(modelo);
        modelo.fireTableDataChanged();
    }//GEN-LAST:event_botonVerMovimientosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerMovimientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMov;
    // End of variables declaration//GEN-END:variables
}
