/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CajeroCarlos;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author InfaSysKey Carlos del Cura Pascual
 * @version 1.0
 * 
 */
public final class SaludoUI extends javax.swing.JPanel implements Runnable{

    private final Usuario usuario;
    private final Tarjeta tarjeta;
    private final Cuenta cuenta;
    
    Thread h1;
    String hora,minutos,segundos;

    /**
     * Creates new form SaludoUI
     */
    public SaludoUI(Cuenta cuenta, Tarjeta tarjeta, Usuario usuario) {
        initComponents();
        this.cuenta = cuenta;
        this.tarjeta = tarjeta;
        this.usuario = usuario;
        h1 = new Thread(this);
        h1.start();
        Date date = new Date();
        DateFormat horaFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat fechaFormat = new SimpleDateFormat("dd/MM/yyyy");
        //txtHora.setText("Hora: " + horaFormat.format(date));
        txtMEs.setText("Fecha Actual : " + fechaFormat.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBancoFassil = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSaludo = new javax.swing.JLabel();
        botonVer = new javax.swing.JButton();
        txtMEs = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        lblSalu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(134, 222, 249));

        labelBancoFassil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCajero/LogoBanco.jpg"))); // NOI18N

        txtSaldo.setBackground(new java.awt.Color(108, 122, 137));
        txtSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(228, 241, 254));
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Saldo");

        lblSaludo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSaludo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botonVer.setBackground(new java.awt.Color(34, 167, 240));
        botonVer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonVer.setForeground(new java.awt.Color(255, 255, 255));
        botonVer.setText("Ver Saldo");
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });

        txtMEs.setBackground(new java.awt.Color(108, 122, 137));
        txtMEs.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMEs.setForeground(new java.awt.Color(228, 241, 254));
        txtMEs.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtHora.setBackground(new java.awt.Color(108, 122, 137));
        txtHora.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHora.setForeground(new java.awt.Color(228, 241, 254));
        txtHora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHora.setToolTipText("");

        lblSalu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSalu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesCajero/AnuncoEvo.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSaludo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelBancoFassil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMEs)
                                    .addComponent(txtHora)))
                            .addComponent(lblSalu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMEs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelBancoFassil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSalu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaludo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaldo)
                    .addComponent(botonVer, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Para saber la hora actual.
     */
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        calendario.setTime(horaActual);
        hora = calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    @Override
    public void run() {
        //WHILE
        Thread current = Thread.currentThread();
        
        while (current == h1) {            
            hora();
            txtHora.setText("Hora Actual : "+hora+":"+minutos+":"+segundos);
        }
    }
    
    /**
     * 
     * @param evt Para ver el saldo y el saludo.
     * 
     */
    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        int saldo = cuenta.getSaldo();
        txtSaldo.setText(saldo + "");
        lblSalu.setText(this.usuario.getNombre() + " " + this.usuario.getApellido());
        lblSaludo.setText("Bienvenido " + this.usuario.getNombre()
                + ", por favor seleccione la operacion a realizar");

    }//GEN-LAST:event_botonVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelBancoFassil;
    private javax.swing.JLabel lblSalu;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMEs;
    private javax.swing.JTextField txtSaldo;
    // End of variables declaration//GEN-END:variables

 
}
